# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

# This docker-compose file contains optional opcua-adapter and opcua-redis services
# for the Magistrala platform. Since this services are optional, this file is dependent on the
# docker-compose.yml file from <project_root>/docker/. In order to run these services,
# core services, as well as the network from the core composition, should be already running.

version: "3.7"

networks:
  magistrala-base-net:

volumes:
  magistrala-twins-db-volume:
  magistrala-twins-db-configdb-volume:

services:
  twins-redis:
    image: redis:7.2.0-alpine
    container_name: magistrala-twins-redis
    restart: on-failure
    networks:
      - magistrala-base-net

  twins-db:
    image: mongo:bionic
    command: mongod --port ${MG_TWINS_DB_PORT}
    container_name: magistrala-twins-db
    restart: on-failure
    environment:
      MONGO_INITDB_DATABASE: ${MG_TWINS_DB_NAME}
    ports:
      - ${MG_TWINS_DB_PORT}:${MG_TWINS_DB_PORT}
    networks:
      magistrala-base-net:
    volumes:
      - magistrala-twins-db-volume:/data/db
      - magistrala-twins-db-configdb-volume:/data/configdb

  twins:
    image: magistrala/twins:${MG_RELEASE_TAG}
    container_name: magistrala-twins
    restart: on-failure
    environment:
      MG_TWINS_LOG_LEVEL: ${MG_TWINS_LOG_LEVEL}
      MG_TWINS_STANDALONE_ID: ${MG_TWINS_STANDALONE_ID}
      MG_TWINS_STANDALONE_TOKEN: ${MG_TWINS_STANDALONE_TOKEN}
      MG_TWINS_CHANNEL_ID: ${MG_TWINS_CHANNEL_ID}
      MG_TWINS_HTTP_HOST: ${MG_TWINS_HTTP_HOST}
      MG_TWINS_HTTP_PORT: ${MG_TWINS_HTTP_PORT}
      MG_TWINS_HTTP_SERVER_CERT: ${MG_TWINS_HTTP_SERVER_CERT}
      MG_TWINS_HTTP_SERVER_KEY: ${MG_TWINS_HTTP_SERVER_KEY}
      MG_TWINS_CACHE_URL: ${MG_TWINS_CACHE_URL}
      MG_ES_URL: ${MG_ES_URL}
      MG_THINGS_STANDALONE_ID: ${MG_THINGS_STANDALONE_ID}
      MG_THINGS_STANDALONE_TOKEN: ${MG_THINGS_STANDALONE_TOKEN}
      MG_TWINS_DB_HOST: ${MG_TWINS_DB_HOST}
      MG_TWINS_DB_PORT: ${MG_TWINS_DB_PORT}
      MG_TWINS_DB_NAME: ${MG_TWINS_DB_NAME}
      MG_AUTH_GRPC_URL: ${MG_AUTH_GRPC_URL}
      MG_AUTH_GRPC_TIMEOUT: ${MG_AUTH_GRPC_TIMEOUT}
      MG_AUTH_GRPC_CLIENT_CERT: ${MG_AUTH_GRPC_CLIENT_CERT:+/auth-grpc-client.crt}
      MG_AUTH_GRPC_CLIENT_KEY: ${MG_AUTH_GRPC_CLIENT_KEY:+/auth-grpc-client.key}
      MG_AUTH_GRPC_SERVER_CA_CERTS: ${MG_AUTH_GRPC_SERVER_CA_CERTS:+/auth-grpc-server-ca.crt}
      MG_MESSAGE_BROKER_URL: ${MG_MESSAGE_BROKER_URL}
      MG_JAEGER_URL: ${MG_JAEGER_URL}
      MG_JAEGER_TRACE_RATIO: ${MG_JAEGER_TRACE_RATIO}
      MG_SEND_TELEMETRY: ${MG_SEND_TELEMETRY}
      MG_TWINS_INSTANCE_ID: ${MG_TWINS_INSTANCE_ID}
    ports:
      - ${MG_TWINS_HTTP_PORT}:${MG_TWINS_HTTP_PORT}
    networks:
       magistrala-base-net:
    depends_on:
      - twins-db
      - twins-redis
    volumes:
      - type: bind
        source: ${MG_ADDONS_CERTS_PATH_PREFIX}${MG_AUTH_GRPC_CLIENT_CERT:-./ssl/certs/dummy/client_cert}
        target: /auth-grpc-client${MG_AUTH_GRPC_CLIENT_CERT:+.crt}
        bind:
          create_host_path: true
      - type: bind
        source: ${MG_ADDONS_CERTS_PATH_PREFIX}${MG_AUTH_GRPC_CLIENT_KEY:-./ssl/certs/dummy/client_key}
        target: /auth-grpc-client${MG_AUTH_GRPC_CLIENT_KEY:+.key}
        bind:
          create_host_path: true
      - type: bind
        source: ${MG_ADDONS_CERTS_PATH_PREFIX}${MG_AUTH_GRPC_SERVER_CA_CERTS:-./ssl/certs/dummy/server_ca}
        target: /auth-grpc-server-ca${MG_AUTH_GRPC_SERVER_CA_CERTS:+.crt}
        bind:
          create_host_path: true
