[[constraint]]
  name = "github.com/asaskevich/govalidator"
  version = "9.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/cisco/senml"

[[constraint]]
  branch = "master"
  name = "github.com/dereulenspiegel/coap-mux"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/dustin/go-coap"

[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.6.0"

[[constraint]]
  name = "github.com/go-zoo/bone"
  version = "1.2.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.1"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/nats-io/go-nats"
  version = "1.4.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/sony/gobreaker"
  version = "0.3.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "gopkg.in/ory-am/dockertest.v3"
  version = "3.1.6"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[prune]
  go-tests = true
  unused-packages = true
