#
# Copyright (c) 2018
# Mainflux
#
# SPDX-License-Identifier: Apache-2.0
#

copyright: Copyright (c) 2015-2019 Mainflux
repo_url: https://github.com/mainflux/mainflux
site_description: Mainflux IoT System
site_name: Mainflux
theme: readthedocs

extra:
  logo: docs/img/logo.png
  author:
    github: mainflux/mainflux
    twitter: mainflux

markdown_extensions:
  - admonition
  - toc:
      permalink: '#'

pages:
- Overview:
    - About: index.md
    - Contributing: CONTRIBUTING.md
    - License: LICENSE.txt
- Architecture: architecture.md
- Getting Started: getting-started.md
- Provisioning: provisioning.md
- Messaging: messaging.md
- Storage: storage.md
- LoRa: lora.md
- Security: 
    - Secure communication: security.md
    - Authentication: authentication.md
- CLI: cli.md
- Bootstrap: bootstrap.md
- Developer's Guide: dev-guide.md
- Load Test: load-test.md
