# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

# This docker-compose file contains optional provision services. Since it's optional, this file is
# dependent of docker-compose file from <project_root>/docker. In order to run this services, execute command:
# docker compose -f docker/docker-compose.yml -f docker/addons/provision/docker-compose.yml up
# from project root.

networks:
  magistrala-base-net:

services:
  provision:
    image: magistrala/provision:${MG_RELEASE_TAG}
    container_name: magistrala-provision
    restart: on-failure
    networks:
      - magistrala-base-net
    ports:
      - ${MG_PROVISION_HTTP_PORT}:${MG_PROVISION_HTTP_PORT}
    environment:
      MG_PROVISION_LOG_LEVEL: ${MG_PROVISION_LOG_LEVEL}
      MG_PROVISION_HTTP_PORT: ${MG_PROVISION_HTTP_PORT}
      MG_PROVISION_CONFIG_FILE: ${MG_PROVISION_CONFIG_FILE}
      MG_PROVISION_ENV_CLIENTS_TLS: ${MG_PROVISION_ENV_CLIENTS_TLS}
      MG_PROVISION_SERVER_CERT: ${MG_PROVISION_SERVER_CERT}
      MG_PROVISION_SERVER_KEY: ${MG_PROVISION_SERVER_KEY}
      MG_PROVISION_USERS_LOCATION: ${MG_PROVISION_USERS_LOCATION}
      MG_PROVISION_CLIENTS_LOCATION: ${MG_PROVISION_CLIENTS_LOCATION}
      MG_PROVISION_USER: ${MG_PROVISION_USER}
      MG_PROVISION_USERNAME: ${MG_PROVISION_USERNAME}
      MG_PROVISION_PASS: ${MG_PROVISION_PASS}
      MG_PROVISION_API_KEY: ${MG_PROVISION_API_KEY}
      MG_PROVISION_CERTS_SVC_URL: ${MG_PROVISION_CERTS_SVC_URL}
      MG_PROVISION_X509_PROVISIONING: ${MG_PROVISION_X509_PROVISIONING}
      MG_PROVISION_BS_SVC_URL: ${MG_PROVISION_BS_SVC_URL}
      MG_PROVISION_BS_CONFIG_PROVISIONING: ${MG_PROVISION_BS_CONFIG_PROVISIONING}
      MG_PROVISION_BS_AUTO_WHITELIST: ${MG_PROVISION_BS_AUTO_WHITELIST}
      MG_PROVISION_BS_CONTENT: ${MG_PROVISION_BS_CONTENT}
      MG_PROVISION_CERTS_HOURS_VALID: ${MG_PROVISION_CERTS_HOURS_VALID}
      MG_SEND_TELEMETRY: ${MG_SEND_TELEMETRY}
      MG_PROVISION_INSTANCE_ID: ${MG_PROVISION_INSTANCE_ID}
    volumes:
      - ./configs:/configs
      - ../../ssl/certs/ca.key:/etc/ssl/certs/ca.key
      - ../../ssl/certs/ca.crt:/etc/ssl/certs/ca.crt
