# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

alarm:
  operations:
    - add: alarm_create_permission
    - view: alarm_read_permission
    - update: alarm_update_permission
    - delete: alarm_delete_permission
  roles_operations:
    - add: manage_role_permission
    - remove: manage_role_permission
    - update: manage_role_permission
    - retrieve: view_role_users_permission
    - retrieve_all: view_role_users_permission
    - add_actions: manage_role_permission
    - list_actions: view_role_users_permission
    - check_actions_exists: view_role_users_permission
    - remove_actions: manage_role_permission
    - remove_all_actions: manage_role_permission
    - add_members: add_role_users_permission
    - list_members: view_role_users_permission
    - check_members_exists: view_role_users_permission
    - remove_members: remove_role_users_permission
    - remove_all_members: remove_role_users_permission

rule:
  operations:
    - add: rule_create_permission
    - view: rule_read_permission
    - update: rule_update_permission
    - update_tags: rule_update_permission
    - update_schedule: rule_update_permission
    - delete: rule_delete_permission
    - enable: rule_update_permission
    - disable: rule_update_permission
  roles_operations:
    - add: manage_role_permission
    - remove: manage_role_permission
    - update: manage_role_permission
    - retrieve: view_role_users_permission
    - retrieve_all: view_role_users_permission
    - add_actions: manage_role_permission
    - list_actions: view_role_users_permission
    - check_actions_exists: view_role_users_permission
    - remove_actions: manage_role_permission
    - remove_all_actions: manage_role_permission
    - add_members: add_role_users_permission
    - list_members: view_role_users_permission
    - check_members_exists: view_role_users_permission
    - remove_members: remove_role_users_permission
    - remove_all_members: remove_role_users_permission

report:
  operations:
    - add: report_create_permission
    - view: report_read_permission
    - update: report_update_permission
    - update_schedule: report_update_permission
    - delete: report_delete_permission
    - enable: report_update_permission
    - disable: report_update_permission
    - generate: report_generate_permission
    - update_template: report_update_permission
    - view_template: report_read_permission
    - delete_template: report_delete_permission
  roles_operations:
    - add: manage_role_permission
    - remove: manage_role_permission
    - update: manage_role_permission
    - retrieve: view_role_users_permission
    - retrieve_all: view_role_users_permission
    - add_actions: manage_role_permission
    - list_actions: view_role_users_permission
    - check_actions_exists: view_role_users_permission
    - remove_actions: manage_role_permission
    - remove_all_actions: manage_role_permission
    - add_members: add_role_users_permission
    - list_members: view_role_users_permission
    - check_members_exists: view_role_users_permission
    - remove_members: remove_role_users_permission
    - remove_all_members: remove_role_users_permission
