# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

version: "3.7"

services:
  nginx:
    depends_on:
      - mqtt-adapter

  mqtt-adapter:
    image: mainflux/mqtt-verne:latest
    container_name: mainflux-mqtt
    depends_on:
      - things
      - nats
    restart: on-failure
    environment:
      MF_MQTT_ADAPTER_LOG_LEVEL: ${MF_MQTT_ADAPTER_LOG_LEVEL}
      MF_MQTT_INSTANCE_ID: mqtt-adapter-1
      MF_MQTT_ADAPTER_ES_URL: tcp://es-redis:${MF_REDIS_TCP_PORT}
      MF_MQTT_ADAPTER_ES_DB: ${MF_MQTT_ADAPTER_ES_DB}
      MF_MQTT_ADAPTER_ES_PASS: ${MF_MQTT_ADAPTER_ES_PASS}
      MF_NATS_URL: ${MF_NATS_URL}
      MF_THINGS_AUTH_GRPC_URL: http://things:${MF_THINGS_AUTH_GRPC_PORT}
      DOCKER_VERNEMQ_PLUGINS__VMQ_PASSWD: "off"
      DOCKER_VERNEMQ_PLUGINS__VMQ_ACL: "off"
      DOCKER_VERNEMQ_PLUGINS__MFX_AUTH: "on"
      DOCKER_VERNEMQ_PLUGINS__MFX_AUTH__PATH: /mainflux/_build/default
      DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL: debug
      MF_MQTT_VERNEMQ_GRPC_POOL_SIZE: 1000
    ports:
      - 18831:${MF_MQTT_ADAPTER_PORT}
      - 8881:${MF_MQTT_ADAPTER_WS_PORT}
      - 7777:8888
    networks:
      - mainflux-base-net
