# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

# This docker-compose file contains optional Timescale and Timescale-writer services
# for Magistrala platform. Since these are optional, this file is dependent of docker-compose file
# from <project_root>/docker. In order to run these services, execute command:
# docker-compose -f docker/docker-compose.yml -f docker/addons/timescale-writer/docker-compose.yml up
# from project root. PostgreSQL default port (5432) is exposed, so you can use various tools for database
# inspection and data visualization.

version: "3.7"

networks:
  magistrala-base-net:

volumes:
  magistrala-timescale-writer-volume:

services:
  timescale:
    image: timescale/timescaledb:2.4.0-pg12
    container_name: magistrala-timescale
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: ${MG_TIMESCALE_PASS}
      POSTGRES_USER: ${MG_TIMESCALE_USER}
      POSTGRES_DB: ${MG_TIMESCALE_NAME}
    ports:
      - 5433:5432
    networks:
      - magistrala-base-net
    volumes:
      - magistrala-timescale-writer-volume:/var/lib/timescalesql/data

  timescale-writer:
    image: magistrala/timescale-writer:${MG_RELEASE_TAG}
    container_name: magistrala-timescale-writer
    depends_on:
      - timescale
    restart: on-failure
    environment:
      MG_TIMESCALE_WRITER_LOG_LEVEL: ${MG_TIMESCALE_WRITER_LOG_LEVEL}
      MG_TIMESCALE_WRITER_CONFIG_PATH: ${MG_TIMESCALE_WRITER_CONFIG_PATH}
      MG_TIMESCALE_WRITER_HTTP_HOST: ${MG_TIMESCALE_WRITER_HTTP_HOST}
      MG_TIMESCALE_WRITER_HTTP_PORT: ${MG_TIMESCALE_WRITER_HTTP_PORT}
      MG_TIMESCALE_WRITER_HTTP_SERVER_CERT: ${MG_TIMESCALE_WRITER_HTTP_SERVER_CERT}
      MG_TIMESCALE_WRITER_HTTP_SERVER_KEY: ${MG_TIMESCALE_WRITER_HTTP_SERVER_KEY}
      MG_TIMESCALE_HOST: ${MG_TIMESCALE_HOST}
      MG_TIMESCALE_PORT: ${MG_TIMESCALE_PORT}
      MG_TIMESCALE_USER: ${MG_TIMESCALE_USER}
      MG_TIMESCALE_PASS: ${MG_TIMESCALE_PASS}
      MG_TIMESCALE_NAME: ${MG_TIMESCALE_NAME}
      MG_TIMESCALE_SSL_MODE: ${MG_TIMESCALE_SSL_MODE}
      MG_TIMESCALE_SSL_CERT: ${MG_TIMESCALE_SSL_CERT}
      MG_TIMESCALE_SSL_KEY: ${MG_TIMESCALE_SSL_KEY}
      MG_TIMESCALE_SSL_ROOT_CERT: ${MG_TIMESCALE_SSL_ROOT_CERT}
      MG_MESSAGE_BROKER_URL: ${MG_MESSAGE_BROKER_URL}
      MG_JAEGER_URL: ${MG_JAEGER_URL}
      MG_JAEGER_TRACE_RATIO: ${MG_JAEGER_TRACE_RATIO}
      MG_SEND_TELEMETRY: ${MG_SEND_TELEMETRY}
      MG_TIMESCALE_WRITER_INSTANCE_ID: ${MG_TIMESCALE_WRITER_INSTANCE_ID}
    ports:
      - ${MG_TIMESCALE_WRITER_HTTP_PORT}:${MG_TIMESCALE_WRITER_HTTP_PORT}
    networks:
      - magistrala-base-net
    volumes:
      - ./config.toml:/config.toml
