# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

# This docker-compose file contains optional InfluxDB and InfluxDB-writer services
# for the Mainflux platform. Since this services are optional, this file is dependent on the
# docker-compose.yml file from <project_root>/docker/. In order to run these services,
# core services, as well as the network from the core composition, should be already running.

version: "3.7"

networks:
  docker_mainflux-base-net:
    external: true

volumes:
  mainflux-influxdb-volume:

services:
  influxdb:
    image: influxdb:2.5
    container_name: mainflux-influxdb
    restart: on-failure
    environment:
      DOCKER_INFLUXDB_INIT_MODE: ${MF_INFLUXDB_INIT_MODE}
      DOCKER_INFLUXDB_INIT_USERNAME: ${MF_INFLUXDB_ADMIN_USER}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${MF_INFLUXDB_ADMIN_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${MF_INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${MF_INFLUXDB_BUCKET}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${MF_INFLUXDB_TOKEN}
      INFLUXDB_HTTP_FLUX_ENABLED: ${MF_INFLUXDB_HTTP_ENABLED}
    networks:
      - docker_mainflux-base-net
    ports:
      - ${MF_INFLUXDB_PORT}:${MF_INFLUXDB_PORT}
    volumes:
      - mainflux-influxdb-volume:/var/lib/influxdb

  influxdb-writer:
    image: mainflux/influxdb-writer:${MF_RELEASE_TAG}
    container_name: mainflux-influxdb-writer
    depends_on:
      - influxdb
    restart: on-failure
    environment:
      MF_INFLUX_WRITER_LOG_LEVEL: debug
      MF_BROKER_URL: ${MF_BROKER_URL}
      MF_INFLUX_WRITER_PORT: ${MF_INFLUX_WRITER_PORT}
      MF_INFLUX_WRITER_BATCH_SIZE: ${MF_INFLUX_WRITER_BATCH_SIZE}
      MF_INFLUX_WRITER_BATCH_TIMEOUT: ${MF_INFLUX_WRITER_BATCH_TIMEOUT}
      MF_INFLUXDB_HOST: ${MF_INFLUXDB_HOST}
      MF_INFLUXDB_PORT: ${MF_INFLUXDB_PORT}
      MF_INFLUXDB_TIMEOUT: ${MF_INFLUXDB_TIMEOUT}
      MF_INFLUXDB_PROTOCOL: ${MF_INFLUXDB_PROTOCOL}
      MF_INFLUXDB_ADMIN_USER: ${MF_INFLUXDB_ADMIN_USER}
      MF_INFLUXDB_ADMIN_PASSWORD: ${MF_INFLUXDB_ADMIN_PASSWORD}
    ports:
      - ${MF_INFLUX_WRITER_PORT}:${MF_INFLUX_WRITER_PORT}
    networks:
      - docker_mainflux-base-net
    volumes:
      - ./config.toml:/config.toml
