# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

###
# This docker-compose file contains optional InfluxDB-reader service for the Mainflux
# platform. Since this service is optional, this file is dependent on the docker-compose.yml
# file from <project_root>/docker/. In order to run this service, core services,
# as well as the network from the core composition, should be already running.
###

version: "3.7"

networks:
  docker_mainflux-base-net:
    external: true

services:
  influxdb-reader:
    image: mainflux/influxdb-reader:${MF_RELEASE_TAG}
    container_name: mainflux-influxdb-reader
    restart: on-failure
    environment:
      MF_INFLUX_READER_LOG_LEVEL: debug
      MF_INFLUX_READER_PORT: ${MF_INFLUX_READER_PORT}
      MF_INFLUXDB_DB: ${MF_INFLUXDB_DB}
      MF_INFLUX_READER_DB_HOST: mainflux-influxdb
      MF_INFLUXDB_PORT: ${MF_INFLUXDB_PORT}
      MF_INFLUXDB_ADMIN_USER: ${MF_INFLUXDB_ADMIN_USER}
      MF_INFLUXDB_ADMIN_PASSWORD: ${MF_INFLUXDB_ADMIN_PASSWORD}
      MF_INFLUX_READER_SERVER_CERT: ${MF_INFLUX_READER_SERVER_CERT}
      MF_INFLUX_READER_SERVER_KEY: ${MF_INFLUX_READER_SERVER_KEY}
      MF_JAEGER_URL: ${MF_JAEGER_URL}
      MF_THINGS_AUTH_GRPC_URL: ${MF_THINGS_AUTH_GRPC_URL}
      MF_THINGS_AUTH_GRPC_TIMEOUT: ${MF_THINGS_AUTH_GRPC_TIMEOUT}
      MF_AUTH_GRPC_URL: ${MF_AUTH_GRPC_URL}
      MF_AUTH_GRPC_TIMEOUT : ${MF_AUTH_GRPC_TIMEOUT}
    ports:
      - ${MF_INFLUX_READER_PORT}:${MF_INFLUX_READER_PORT}
    networks:
      - docker_mainflux-base-net
    volumes:
      - ../../ssl/certs:/etc/ssl/certs
