# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

# This docker-compose file contains optional MongoDB and MongoDB-writer services
# for Mainflux platform. Since these are optional, this file is dependent of docker-compose file
# from <project_root>/docker. In order to run these services, execute command:
# docker-compose -f docker/docker-compose.yml -f docker/addons/mongodb-writer/docker-compose.yml up
# from project root. MongoDB default port (27017) is exposed, so you can use various tools for database
# inspection and data visualization.

version: "3.7"

networks:
  docker_mainflux-base-net:
    external: true

volumes:
  mainflux-mongodb-db-volume:
  mainflux-mongodb-configdb-volume:

services:
  mongodb:
    image: mongo:4.4.3-bionic
    container_name: mainflux-mongodb
    restart: on-failure
    environment:
      MONGO_INITDB_DATABASE: ${MF_MONGO_WRITER_DB}
    ports:
      - ${MF_MONGO_WRITER_DB_PORT}:${MF_MONGO_WRITER_DB_PORT}
    networks:
      - docker_mainflux-base-net
    volumes:
      - mainflux-mongodb-db-volume:/data/db
      - mainflux-mongodb-configdb-volume:/data/configdb

  mongodb-writer:
    image: mainflux/mongodb-writer:${MF_RELEASE_TAG}
    container_name: mainflux-mongodb-writer
    depends_on:
      - mongodb
    restart: on-failure
    environment:
      MF_MONGO_WRITER_LOG_LEVEL: ${MF_MONGO_WRITER_LOG_LEVEL}
      MF_NATS_URL: ${MF_NATS_URL}
      MF_MONGO_WRITER_PORT: ${MF_MONGO_WRITER_PORT}
      MF_MONGO_WRITER_DB: ${MF_MONGO_WRITER_DB}
      MF_MONGO_WRITER_DB_HOST: mongodb
      MF_MONGO_WRITER_DB_PORT: ${MF_MONGO_WRITER_DB_PORT}
      MF_MONGO_WRITER_TRANSFORMER: ${MF_MONGO_WRITER_TRANSFORMER}
    ports:
      - ${MF_MONGO_WRITER_PORT}:${MF_MONGO_WRITER_PORT}
    networks:
      - docker_mainflux-base-net
    volumes:
      - ./config.toml:/config.toml
