###
# This docker-compose file contains optional MongoDB and MongoDB-writer services
# for Mainflux platform. Since these are optional, this file is dependent of docker-compose file
# from <project_root>/docker. In order to run these optional service, execute command:
# docker-compose -f docker/docker-compose.yml -f docker/addons/mongodb-writer/docker-compose.yml up
# from project root. MongoDB default port (27017) is exposed, so you can use various tools for database
# inspection and data visualization.
###

version: "3"

networks:
  docker_mainflux-base-net:
    external: true

services:
  mongodb:
    image: mongo:3.6-jessie
    container_name: mainflux-mongodb
    restart: on-failure
    environment:
      MONGO_INITDB_DATABASE: mainflux
    ports:
      - 27017:27017
    networks:
      - docker_mainflux-base-net

  mongodb-writer:
    image: mainflux/mongodb-writer:latest
    container_name: mainflux-mongodb-writer
    depends_on:
      - mongodb
    restart: on-failure
    environment:
      MF_MONGO_WRITER_LOG_LEVEL: debug
      MF_NATS_URL: nats://nats:4222
      MF_MONGO_WRITER_PORT: 8901
      MF_MONGO_WRITER_DB_NAME: mainflux
      MF_MONGO_WRITER_DB_HOST: mongodb
      MF_MONGO_WRITER_DB_PORT: 27017
    ports:
      - 8901:8901
    networks:
      - docker_mainflux-base-net
