# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

# This docker-compose file contains optional MongoDB and MongoDB-writer services
# for Magistrala platform. Since these are optional, this file is dependent of docker-compose file
# from <project_root>/docker. In order to run these services, execute command:
# docker-compose -f docker/docker-compose.yml -f docker/addons/mongodb-writer/docker-compose.yml up
# from project root. MongoDB default port (27017) is exposed, so you can use various tools for database
# inspection and data visualization.

version: "3.7"

networks:
  magistrala-base-net:

volumes:
  magistrala-mongodb-db-volume:
  magistrala-mongodb-configdb-volume:

services:
  mongodb:
    image: mongo:4.4.6
    container_name: magistrala-mongodb
    restart: on-failure
    environment:
      MONGO_INITDB_DATABASE: ${MG_MONGO_NAME}
    ports:
      - ${MG_MONGO_PORT}:${MG_MONGO_PORT}
    networks:
      - magistrala-base-net
    volumes:
      - magistrala-mongodb-db-volume:/data/db
      - magistrala-mongodb-configdb-volume:/data/configdb

  mongodb-writer:
    image: magistrala/mongodb-writer:${MG_RELEASE_TAG}
    container_name: magistrala-mongodb-writer
    depends_on:
      - mongodb
    restart: on-failure
    environment:
      MG_MONGO_WRITER_LOG_LEVEL: ${MG_MONGO_WRITER_LOG_LEVEL}
      MG_MONGO_WRITER_CONFIG_PATH: ${MG_MONGO_WRITER_CONFIG_PATH}
      MG_MONGO_WRITER_HTTP_HOST: ${MG_MONGO_WRITER_HTTP_HOST}
      MG_MONGO_WRITER_HTTP_PORT: ${MG_MONGO_WRITER_HTTP_PORT}
      MG_MONGO_WRITER_HTTP_SERVER_CERT: ${MG_MONGO_WRITER_HTTP_SERVER_CERT}
      MG_MONGO_WRITER_HTTP_SERVER_KEY: ${MG_MONGO_WRITER_HTTP_SERVER_KEY}
      MG_MONGO_HOST: ${MG_MONGO_HOST}
      MG_MONGO_PORT: ${MG_MONGO_PORT}
      MG_MONGO_NAME: ${MG_MONGO_NAME}
      MG_MESSAGE_BROKER_URL: ${MG_MESSAGE_BROKER_URL}
      MG_JAEGER_URL: ${MG_JAEGER_URL}
      MG_JAEGER_TRACE_RATIO: ${MG_JAEGER_TRACE_RATIO}
      MG_SEND_TELEMETRY: ${MG_SEND_TELEMETRY}
      MG_MONGO_WRITER_INSTANCE_ID: ${MG_MONGO_WRITER_INSTANCE_ID}
    ports:
      - ${MG_MONGO_WRITER_HTTP_PORT}:${MG_MONGO_WRITER_HTTP_PORT}
    networks:
      - magistrala-base-net
    volumes:
      - ./config.toml:/config.toml
