# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  swagger-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Swagger UI action
        id: swagger-ui-action
        uses: blokovi/swagger-ui-action@main
        with:
          dir: "./api/openapi"
          pattern: "*.yml"
          debug: "true"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui
          cname: api.mainflux.io
